[server]
maxUploadSize = 5
enableXsrfProtection = false
enableCORS = true
port = 8501
address = "localhost"

[browser]
serverAddress = "localhost"
gatherUsageStats = false

[theme]
base = "light"

[client]
toolbarMode = "minimal"
showErrorDetails = true

[runner]
magicEnabled = true
fastReruns = true
postScriptGC = true

[logger]
level = "info"

[caching]
enable = true
maxEntries = 100
ttl = 3600

[global]
developmentMode = false
